# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: akashpgp24
# "service" is the name of this project. This will also be added to your AWS resource names.
service: produx

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
